// T-019 — Zustand store + engine ↔ UI bridge.
//
// The store is the single point of contact between the headless engine and all
// React components. Components read from the store via selectors and push
// decisions back via `enqueueDecision`. The UI never mutates `snapshot`
// directly — it is a view-only consumer of `engine.tick()` snapshots and the
// event bus.
//
// Engine ↔ UI contract (locked in Decisions Log):
//   - engine.applyDecisions(decisions)  — queued; drained at stage 0 next tick
//   - engine.tick()                     — runs the pipeline, returns snapshot
//   - engine.subscribe(listener)        — event stream
//
// Same-tick mutation is forbidden: `enqueueDecision` only enqueues; the engine
// drains at stage 0 of the next tick. See CLAUDE.md invariant #3.

import { create, type StoreApi, type UseBoundStore } from 'zustand'

import { createEngine } from '@engine'
import { createAureliaState } from '@engine/fixtures/aurelia'
import { EVENT_FEED_LENGTH } from '@engine/tunables'
import type {
  Decision,
  Engine,
  EngineEvent,
  EngineState,
} from '@engine'

export type GameStoreState = {
  /** Latest engine snapshot. Read-only from the UI's perspective. */
  snapshot: EngineState
  /** Recent engine events, FIFO, capped at EVENT_FEED_LENGTH. */
  events: EngineEvent[]
  /**
   * Tick speed multiplier. 0 = paused; 1/2/4 from `SPEEDS`. The store does not
   * drive the tick loop — that lives in `useTickLoop` (T-020). `setSpeed(0)`
   * is just a state write here.
   */
  speed: number

  /** Run one engine tick and store the resulting snapshot. */
  advance: () => void
  /** Queue a decision for the next tick (no same-tick application). */
  enqueueDecision: (decision: Decision) => void
  /** Set the desired tick speed; the tick loop reads this in T-020. */
  setSpeed: (speed: number) => void
}

export type GameStoreOptions = {
  /** PRNG seed for the engine. Required so tests can lock determinism. */
  seed: number
  /**
   * Optional pre-built engine state. Defaults to `createAureliaState()`. Tests
   * can pass a mutated fixture to drive specific scenarios.
   */
  initialState?: EngineState
  /**
   * Initial UI tick speed. Defaults to 0 (paused). The store does not drive
   * the tick loop — this is a UI hint consumed by `useTickLoop` in T-020.
   */
  initialSpeed?: number
}

export type GameStore = UseBoundStore<StoreApi<GameStoreState>> & {
  /**
   * Engine handle owned by this store. Exposed for diagnostics / tests; UI
   * code must NEVER call these methods directly — go through the store actions
   * so events and snapshots stay in sync.
   */
  engine: Engine
  /** Tear down the engine subscription (used by tests that recreate stores). */
  destroy: () => void
}

/**
 * Factory for an isolated game store. Each call wires a fresh engine + a fresh
 * Zustand store + a one-time event subscription. Tests use this directly so
 * each test gets a clean, deterministic slate. App code uses the singleton
 * `useGameStore` below.
 */
export function createGameStore(options: GameStoreOptions): GameStore {
  const { seed, initialState, initialSpeed = 0 } = options

  // Build the engine first so the store's initial snapshot can be the
  // un-ticked starting state. The first `advance()` the UI calls then
  // advances tick from 0 → 1 (AC #1).
  const seedState = initialState ?? createAureliaState()
  const engine = createEngine(seedState, { seed })

  const store = create<GameStoreState>((set) => ({
    snapshot: seedState,
    events: [],
    speed: initialSpeed,

    advance: () => {
      const nextSnapshot = engine.tick()
      set({ snapshot: nextSnapshot })
    },

    enqueueDecision: (decision: Decision) => {
      // Push-only to the engine queue. The engine drains it at stage 0 of the
      // next tick — same-tick mutation is forbidden (CLAUDE.md invariant #3).
      engine.applyDecisions([decision])
      // Intentionally no state mutation here: the UI sees the change only
      // after the next `advance()` flushes through the pipeline.
    },

    setSpeed: (speed: number) => set({ speed }),
  }))

  // Subscribe once to the engine event stream and push to `events`, FIFO,
  // capped at EVENT_FEED_LENGTH (oldest dropped on overflow). The bus flushes
  // at the end of `engine.tick()`, so all events generated by a single
  // `advance()` arrive synchronously before the snapshot setter resolves.
  const unsubscribe = engine.subscribe((event: EngineEvent) => {
    store.setState((prev) => {
      const next = [...prev.events, event]
      if (next.length > EVENT_FEED_LENGTH) {
        // Drop oldest entries until we are back at the cap.
        next.splice(0, next.length - EVENT_FEED_LENGTH)
      }
      return { events: next }
    })
  })

  const boundStore = store as GameStore
  boundStore.engine = engine
  boundStore.destroy = () => {
    unsubscribe()
  }
  return boundStore
}

// --- Singleton ------------------------------------------------------------
//
// `useGameStore` is the singleton hook React components import. It builds an
// engine seeded from the URL (`?seed=`) if present, else `Date.now()`. Tests
// MUST NOT use this singleton — they should construct their own store via
// `createGameStore({ seed: <fixed> })` so each test is hermetic.

function resolveBootSeed(): number {
  if (typeof window === 'undefined') {
    return Date.now()
  }
  const raw = new URLSearchParams(window.location.search).get('seed')
  if (raw === null) {
    return Date.now()
  }
  const parsed = parseInt(raw, 10)
  return Number.isFinite(parsed) ? parsed : Date.now()
}

let singleton: GameStore | null = null

/**
 * Lazy-initialized singleton accessor. The first call constructs the store
 * (seeded from the URL or `Date.now()`); subsequent calls return the same
 * instance. Tests MUST construct their own store via `createGameStore` rather
 * than touch this singleton.
 */
export function getGameStore(): GameStore {
  if (singleton === null) {
    singleton = createGameStore({ seed: resolveBootSeed() })
  }
  return singleton
}

/**
 * Reset the singleton — for tests that explicitly need to exercise the
 * boot-from-URL path. App code should never call this.
 */
export function resetGameStoreSingleton(): void {
  if (singleton !== null) {
    singleton.destroy()
    singleton = null
  }
}

/**
 * Singleton React hook. Components import this and call it with a selector
 * (`useGameStore((s) => s.snapshot.tick)`) so they re-render only when their
 * selected slice changes (Zustand referential equality by default).
 *
 * Forwarded straight to the singleton store; the singleton is constructed on
 * first call. Calling without a selector returns the full state (Zustand's
 * default behavior) — prefer a selector to keep re-renders minimal.
 */
export function useGameStore<T>(selector: (state: GameStoreState) => T): T
export function useGameStore(): GameStoreState
export function useGameStore<T>(selector?: (state: GameStoreState) => T): T | GameStoreState {
  const store = getGameStore()
  // Zustand's bound hook is itself a function with two overloads (no args = full state).
  // We forward unconditionally; the cast is safe because the hook resolves the right one.
  if (selector === undefined) return store()
  return store(selector)
}
